<?php
require_once("../mysql-lib.php");
require_once("../debug.php");


// turn on the generator here
generatePosterRecordInFile();



function generatePosterRecordInFile()
{
    $conn = null;
    $defaultZwibblerDoc = '[{"id":0,"type":"GroupNode","fillStyle":"#cccccc","strokeStyle":"#000000","lineWidth":2,"shadow":false,"matrix":[1,0,0,1,0,0],"layer":"default"},{"id":1,"type":"PageNode","parent":0,"fillStyle":"#cccccc","strokeStyle":"#000000","lineWidth":2,"shadow":false,"matrix":[1,0,0,1,0,0],"layer":"default"},{"id":2,"type":"TextNode","parent":1,"fillStyle":"#000000","strokeStyle":"#000000","lineWidth":0,"shadow":false,"matrix":[1,0,0,2.2499999999999996,43.5,262],"layer":"default","textFillStyle":"#000000","fontName":"Arial","fontSize":20,"wrap":false,"textAlign":"left","bold":false,"italic":false,"text":"This record is auto generated by unit_test/poster-generator.php, so no ZwibblerDoc to show."},{"id":3,"type":"TextNode","parent":1,"fillStyle":"#000000","strokeStyle":"#000000","lineWidth":0,"shadow":false,"matrix":[2.108717109062248,0,0,2.108717109062248,296.5,179.17434218124495],"layer":"default","textFillStyle":"#000000","fontName":"Arial","fontSize":20,"wrap":false,"textAlign":"left","bold":false,"italic":false,"text":"DO NOT PANIC!"}]';

    try {
        $conn = db_connect();

        foreach (glob("../poster_img/*.png") as $imageUrl) {
            $col = explode("_", explode(".", explode("/", $imageUrl, 3)[2])[0], 3);
            $studentID = $col[0];
            $quizID = $col[1];
            $status = "UNGRADED";

            $conn->beginTransaction();
            updatePosterSubmission($conn, $quizID, $studentID, $defaultZwibblerDoc, $imageUrl);
            updateQuizRecord($conn, $quizID, $studentID, $status);

            $conn->commit();
            echo "[SUCCESS]";
            echo "INSERT INTO `isnap2changedb`.`poster_record` (`StudentID`, `QuizID`, 'ZwibblerDoc',`ImageURL`) VALUES ($studentID,$quizID,'sample zwibbler doc', $imageUrl);";
            echo "<br>";
            echo "[SUCCESS]";
            echo "INSERT INTO `isnap2changedb`.`quiz_record` (`StudentID`, `QuizID`, `Status`) VALUES ($studentID,$quizID, '$status');";
            echo "<br>";

        }
    } catch (Exception $e) {
        if ($conn != null) {
            $conn->rollBack();
            db_close($conn);
        }
        debug_err($e);
    }

    db_close($conn);
}


?>

